language: generic
os: osx
compiler: gcc
matrix:
        include:
                - os: linux
                  env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
                  addons:
                  apt:
                  packages:
                          - g++-7
                  sources: &sources
                          - ubuntu-toolchain-r-test
before_install:
        - echo "Package: gcc-7" >> /etc/apt/preferences
        - echo "Pin: release n=zesty" >> /etc/apt/preferences
        - echo "Pin-Priority: 990" >> /etc/apt/preferences
        - sudo apt-get -qq update
install:
        - sudo apt-get install -qq gcc-7
script:
        - make
        - wget http://www.ece.rice.edu/~wakin/images/lena512color.tiff
        - convert -compress none lena512color.tiff lena.ppm
        - ./jpezy lena.ppm output.jpg
        - file output.jpg 
