language: cpp
script:
        - g++-7 --version
        - g++ -I. -std=c++1z -Wall -Wextra -pedantic -o jpezy src/main.cpp
        - wget http://www.ece.rice.edu/~wakin/images/lena512color.tiff
        - convert -compress none lena512color.tiff lena.ppm
        - ./jpezy lena.ppm output.jpg
        - ls -l output.jpg
        - file output.jpg
compiler:
        - gcc-7
install:
        - git clone https://github.com/falgon/SrookCppLibraries.git
        - mv SrookCppLibraries/srook .
        - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
        - sudo add-apt-repository --yes 'deb http://us.archive.ubuntu.com/ubuntu wily main universe'
        - sudo apt-get install build-essential software-properties-common -y 
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get -qq upgrade
        - sudo apt-get -qq install libboost-all-dev
        - sudo apt-get -qq install gcc-7 g++-7
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7 \
        - sudo update-alternatives --config gcc
