language: generic
os: osx
compiler: gcc
matrix:
        include:
                - os: linux
                  env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
                  addons:
                  apt:
                  packages:
                          - g++-7
                  sources: &sources
                          - ubuntu-toolchain-r-test
script:
        - make
        - wget http://www.ece.rice.edu/~wakin/images/lena512color.tiff
        - convert -compress none lena512color.tiff lena.ppm
        - ./jpezy lena.ppm output.jpg
        - file output.jpg 
